# Generated by Django 5.2.7 on 2025-11-05 08:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_type', models.CharField(choices=[('myself', 'Myself'), ('others', 'Others')], max_length=20)),
                ('passenger_name', models.CharField(blank=True, max_length=100, null=True)),
                ('passenger_aadhaar', models.CharField(blank=True, max_length=12, null=True)),
                ('passenger_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('passenger_age', models.PositiveIntegerField(blank=True, null=True)),
                ('passenger_gender', models.CharField(blank=True, max_length=20, null=True)),
                ('passenger_relationship', models.CharField(blank=True, max_length=50, null=True)),
                ('special_requirements', models.JSONField(blank=True, default=list)),
                ('pickup_location', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('ride_type', models.CharField(choices=[('Standard', 'Standard SafeRide'), ('Women Only', 'Women Only'), ('Kids Friendly', 'Kids Friendly'), ('Wheelchair Accessible', 'Wheelchair Accessible'), ('Elderly Care', 'Elderly Care'), ('Medical Transport', 'Medical Transport')], max_length=30)),
                ('passengers_count', models.PositiveIntegerField(default=1)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100, null=True)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
